version: 0.2

phases:
    install:
        commands:
            - project_name=aws_webscraping_layer
            - /bin/bash codebuild/install.sh
    pre_build:
        commands:
            - /bin/bash codebuild/prebuild.sh
    build:
        commands:
            - /bin/bash codebuild/build.sh
    post_build:
        commands:
            - /bin/bash codebuild/postbuild.sh
